package com.salma.moviereviewsapp.model

import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName
import com.salma.moviereviewsapp.util.Constants
import kotlinx.serialization.Serializable

@Serializable
@Entity(tableName = Constants.MOVIE_TABLE)
data class Movie(
    @SerializedName("display_title")
    val title: String,

    @SerializedName("byline")
    val reviewer: String,

    @SerializedName("mpaa_rating")
    val rating: String,

    @SerializedName("summary_short")
    val summary: String,

    @SerializedName("publication_date")
    val date: String,

    @Embedded
    val multimedia: MovieMultimedia,

    @PrimaryKey val id: Int? = null, //generated by Room,
)
