package com.salma.moviereviewsapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.salma.moviereviewsapp.util.Constants
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@Entity(tableName = Constants.MOVIE_TABLE)
data class Movie(
    @SerialName("display_title")
    val title: String,

    @SerialName("byline")
    val reviewer: String,

    @SerialName("mpaa_rating")
    val rating: String,

    @SerialName("summary_short")
    val summary: String,

    @SerialName("publication_date")
    val date: String,

    @PrimaryKey val id: Int? = null, //generated by Room,
)
