package com.salma.moviereviewsapp.model

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.salma.moviereviewsapp.util.Constants
import kotlinx.serialization.Serializable

@Serializable
@Entity(tableName = Constants.MOVIE_TABLE)
data class Movie(
    val title: String,
    val reviewer: String,
    val rating: String,
    val summary: String,
    val date: String,
    @PrimaryKey val id: Int? = null, //generated by Room,
)
